version: 2.1
jobs:
  build:
    docker:
      - image: python:2.7
      - image: mysql:5.7.19
        environment:
          MYSQL_ROOT_PASSWORD: nylas_it
          MYSQL_USER: inboxtest
          MYSQL_PASSWORD: inboxtest
    working_directory: ~/inbox

    steps:
      - checkout

      - run:
          name: install dependencies
          command: |
            virtualenv venv
            . venv/bin/activate
            pip install -r requirements_frozen.txt

      - run:
          name: run tests
          command: |
            . venv/bin/activate
            tox
